version: '3'
services:
  golang:
    build: ./
    ports:
      - "3002:8080"
    container_name: calendar_backend
    volumes:
      - "./:/calendar_backend/"
    depends_on:
      - mysql  
  mysql:
    build: ./infrastructure/db/
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      GOROOT: /golang_calendar
      TZ: "Asia/Tokyo"
    container_name: calendar_mysql
    hostname: calendar_mysql
    volumes:
      - "./infrastructure/db/data:/var/lib/mysql"
      - "./infrastructure/db/initdb.d:/docker-entrypoint-initdb.d"
