// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSchedule struct {
	UserID  *int    `json:"userId"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
	Memo    *string `json:"memo"`
	StartAt *string `json:"StartAt"`
	EndAt   *string `json:"EndAt"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Schedule struct {
	UserID  *int    `json:"userId"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
	Memo    *string `json:"memo"`
	StartAt *string `json:"StartAt"`
	EndAt   *string `json:"EndAt"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
	Email    *string `json:"email"`
}
